language: haskell
ghc:
  - "7.4"
  - "7.6"
  - "7.8"
  - "7.10"
  - "8.0"
  - "8.2"
  - "8.4"
install:
  - "cabal install --dry-run -v3"
  - "travis_retry cabal install --only-dependencies --enable-test --force-reinstalls"
script:
  - "cabal install --jobs=1"
notifications:
  email:
    recipients: travis@silk.co
    on_success: never
    on_failure: change
